### ISSUE TITLE
Unable to make it working globally

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [TechnologyAdvice/Cryptex#9]
I have installed Cryptex globally and created cryptex.json in the current working directory. Added the following configuration in it.

`{
  "development": {
    "keySource": "none",
    "algorithm": "plaintext",
    "secretEncoding": "utf8"
  }
}`

I run the tool like `cryptex -edevelopment encrypt mypassword` but nothing happening. It is showing the help message.

Please let me know if i 'm using it right?

**Comment by TomFrost** [comment]
Was `-edevelopment` a typo? If not, put a space in it like this: `-e development` :)

**Comment by TomFrost** [comment]
Also-- I'm on mobile right now and can't confirm, but I believe you need to put the -e flag _after_ `encrypt`.

**Comment by UnnikrishnanBhargavakurup** [comment]
@TomFrost - Yes you are right it's working fine with `-e` flag after encrypt `cryptex encrypt mypassword -e development`

Thanks for the help!

**Comment by TomFrost** [comment]
Glad you got it working!
